name: convert source to pdf

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: HTML to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: 'resume.html'
          outputFile: 'resume.pdf'
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
  commit-and-push:
    needs: create-pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: commit and push pdf
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git config --global user.email 'cameronwatson98@protonmail.com'
          git config --global user.name 'Cameron Watson'
          git commit -m "generated pdf"
          git push
